version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./laudos:/app/laudos
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    restart: unless-stopped
