# Generated by Django 5.2.4 on 2025-07-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaIdentificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(blank=True, max_length=14, null=True)),
                ('data_emissao', models.DateField()),
                ('orgao_emissor', models.CharField(max_length=2)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('União Estável', 'União Estável')], max_length=20)),
                ('mae', models.CharField(max_length=255)),
                ('pai', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_formacao', models.CharField(blank=True, choices=[('Ensino Fundamental Incompleto', 'Ensino Fundamental Incompleto'), ('Ensino Fundamental Completo', 'Ensino Fundamental Completo'), ('Ensino Médio Incompleto', 'Ensino Médio Incompleto'), ('Ensino Médio Completo', 'Ensino Médio Completo'), ('Ensino Superior Incompleto', 'Ensino Superior Incompleto'), ('Ensino Superior Completo', 'Ensino Superior Completo'), ('Pós-Graduação Incompleta', 'Pós-Graduação Incompleta'), ('Pós-Graduação Completa', 'Pós-Graduação Completa'), ('Mestrado Incompleto', 'Mestrado Incompleto'), ('Mestrado Completo', 'Mestrado Completo'), ('Doutorado Incompleto', 'Doutorado Incompleto'), ('Doutorado Completo', 'Doutorado Completo'), ('Nenhum', 'Nenhum')], max_length=50, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deficiente', models.CharField(max_length=10)),
                ('deficiencia', models.CharField(blank=True, max_length=255, null=True)),
                ('familia_cad_unico', models.CharField(max_length=10)),
                ('beneficio_social', models.CharField(max_length=30)),
                ('aposentadoria', models.CharField(max_length=20)),
                ('passe_intermunicipal', models.CharField(max_length=10)),
                ('passe_interestadual', models.CharField(max_length=10)),
                ('carteira_autista', models.CharField(max_length=20)),
                ('laudo', models.CharField(max_length=10)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
