# Generated by Django 5.2.4 on 2025-07-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaidentificacao',
            name='aposentadoria',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fichaidentificacao',
            name='beneficio_social',
            field=models.CharField(blank=True, choices=[('Bolsa Família', 'Bolsa Família'), ('Auxílio Brasil', 'Auxílio Brasil'), ('BPC - Benefício de Prestação Continuada', 'BPC - Benefício de Prestação Continuada'), ('Auxilio por Incapacidade Temporária', 'Auxilio por Incapacidade Temporária'), ('Auxilio por Incapacidade Permanente', 'Auxilio por Incapacidade Permanente'), ('Outro', 'Outro'), ('Nenhum', 'Nenhum')], max_length=39),
        ),
        migrations.AlterField(
            model_name='fichaidentificacao',
            name='carteira_autista',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fichaidentificacao',
            name='deficiente',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichaidentificacao',
            name='familia_cad_unico',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichaidentificacao',
            name='laudo',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichaidentificacao',
            name='passe_interestadual',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fichaidentificacao',
            name='passe_intermunicipal',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10),
        ),
    ]
