# Generated by Django 5.2.4 on 2025-07-23 17:16

import ficha.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_alter_fichaidentificacao_aposentadoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaidentificacao',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único da ficha', unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='fichaidentificacao',
            name='observacao',
            field=models.FileField(blank=True, null=True, upload_to=ficha.models.laudo_upload_path, verbose_name='Observações do Laudo (PDF)'),
        ),
    ]
