# Generated by Django 5.2.4 on 2025-07-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_fichaidentificacao_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaidentificacao',
            name='livre_cultura',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
