# Generated by Django 5.2.4 on 2025-07-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_fichaidentificacao_livre_cultura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaidentificacao',
            name='livre_cultura',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=10),
        ),
    ]
